import { useCallback, useEffect, useState } from "react";
import Swal from "sweetalert2";
import { getAdminQuanTriVien, postAdminQuanTriVien, putAdminQuanTriVien } from "../../api/hotel_booking_api";
import AdminIcon from "../../components/admin/AdminIcon";
import AdminLayout from "../../components/admin/AdminLayout";
import AdminPagination from "../../components/admin/AdminPagination";
import { formatDate } from "../../utils/format";
import "../../styles/admin-phong.css";

const empty = { ho_ten: "", email: "", so_dien_thoai: "", mat_khau: "" };
export default function AdminQuanTriVien() {
  const [data, setData] = useState([]), [q, setQ] = useState(""), [meta, setMeta] = useState(null), [loading, setLoading] = useState(true), [form, setForm] = useState(null), [editing, setEditing] = useState(null), [errors, setErrors] = useState({}), [saving, setSaving] = useState(false);
  const load = useCallback(async (page = 1) => { try { setLoading(true); const r = await getAdminQuanTriVien({ tim_kiem: q, page }); if (!r.success) throw new Error(r.message); setData(r.data || []); setMeta(r.pagination); } catch (e) { await Swal.fire({ icon: "error", title: "Không thể tải quản trị viên", text: e.response?.data?.message || e.message }); } finally { setLoading(false); } }, [q]);
  useEffect(() => { load(1); }, [load]);
  const openAdd = () => { setEditing(null); setForm(empty); setErrors({}); };
  const openEdit = (item) => { setEditing(item); setForm({ ho_ten: item.ho_ten, email: item.email, so_dien_thoai: item.so_dien_thoai || "", mat_khau: "" }); setErrors({}); };
  const change = (e) => { const { name, value } = e.target; setForm((old) => ({ ...old, [name]: value })); setErrors((old) => ({ ...old, [name]: "" })); };
  const save = async (e) => { e.preventDefault(); try { setSaving(true); const payload = { ...form }; if (editing && !payload.mat_khau) delete payload.mat_khau; const r = editing ? await putAdminQuanTriVien(editing.id, payload) : await postAdminQuanTriVien(payload); if (!r.success) throw new Error(r.message); setForm(null); await Swal.fire({ icon: "success", title: r.message }); load(); } catch (e) { if (e.response?.data?.errors) setErrors(Object.fromEntries(Object.entries(e.response.data.errors).map(([k,v]) => [k,v[0]]))); else await Swal.fire({ icon: "error", title: "Không thể lưu", text: e.response?.data?.message || e.message }); } finally { setSaving(false); } };
  return <AdminLayout title="Quản lý quản trị viên" activeMenu="quan-tri-vien"><main className="admin-content"><div className="admin-intro admin-room-intro"><div><p className="section-kicker">TÀI KHOẢN QUẢN TRỊ</p><h2>Quản lý quản trị viên</h2><p>Thêm và cập nhật các tài khoản có quyền quản trị.</p></div><button type="button" onClick={openAdd}>+ Thêm quản trị viên</button></div><div className="admin-room-toolbar"><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Tìm tên, email, số điện thoại..."/><button type="button" onClick={() => load(1)}>Tìm kiếm</button></div>{loading ? <div className="admin-room-loading">Đang tải...</div> : <><div className="admin-table-wrap"><table className="admin-room-table"><thead><tr><th>Quản trị viên</th><th>Liên hệ</th><th>Ngày tạo</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{data.length === 0 ? <tr><td colSpan="5" className="admin-table-empty">Chưa có quản trị viên phù hợp.</td></tr> : data.map((item) => <tr key={item.id}><td><strong>{item.ho_ten}</strong></td><td>{item.email}<br/><small>{item.so_dien_thoai || "—"}</small></td><td>{formatDate(item.created_at)}</td><td><span className={item.trang_thai === "hoat_dong" ? "admin-room-status" : "admin-room-status admin-room-status-inactive"}>{item.trang_thai === "hoat_dong" ? "Hoạt động" : "Đã khóa"}</span></td><td><div className="admin-room-actions"><button className="admin-icon-button icon-gold" title="Sửa quản trị viên" onClick={() => openEdit(item)}><AdminIcon name="edit"/></button></div></td></tr>)}</tbody></table></div><AdminPagination pagination={meta} onPageChange={load}/></>}</main>{form && <div className="admin-modal-backdrop"><section className="admin-room-modal" role="dialog"><div className="admin-modal-head"><div><p className="section-kicker">TÀI KHOẢN QUẢN TRỊ</p><h2>{editing ? "Cập nhật quản trị viên" : "Thêm quản trị viên"}</h2></div><button type="button" onClick={() => setForm(null)}>×</button></div><form noValidate onSubmit={save}><div className="admin-form-grid">{[["ho_ten","Họ và tên *","text"],["email","Email *","email"],["so_dien_thoai","Số điện thoại","text"],["mat_khau",editing ? "Mật khẩu mới (để trống nếu giữ nguyên)" : "Mật khẩu *","password"]].map(([name,label,type]) => <label key={name}>{label}<input name={name} type={type} value={form[name]} onChange={change} className={errors[name] ? "is-invalid" : ""}/>{errors[name] && <div className="invalid-feedback">{errors[name]}</div>}</label>)}</div><div className="admin-form-actions"><button type="button" onClick={() => setForm(null)}>Hủy</button><button type="submit" disabled={saving}>{saving ? "Đang lưu..." : "Lưu quản trị viên"}</button></div></form></section></div>}</AdminLayout>;
}
