import { useCallback, useEffect, useState } from "react";
import Swal from "sweetalert2";
import { getAdminLienHe, getChiTietAdminLienHe, putTrangThaiAdminLienHe } from "../../api/hotel_booking_api";
import AdminIcon from "../../components/admin/AdminIcon";
import AdminLayout from "../../components/admin/AdminLayout";
import AdminPagination from "../../components/admin/AdminPagination";
import ReactSelect from "../../components/ReactSelect";
import { formatDateTime } from "../../utils/format";
import "../../styles/admin-phong.css";

export default function AdminLienHe() {
  const [data, setData] = useState([]), [q, setQ] = useState(""), [status, setStatus] = useState(""), [meta, setMeta] = useState(null), [loading, setLoading] = useState(true), [detail, setDetail] = useState(null);
  const load = useCallback(async (page = 1) => { try { setLoading(true); const r = await getAdminLienHe({ tim_kiem: q, trang_thai: status, page }); if (!r.success) throw new Error(r.message); setData(r.data || []); setMeta(r.pagination); } catch (e) { await Swal.fire({ icon: "error", title: "Không thể tải liên hệ", text: e.response?.data?.message || e.message }); } finally { setLoading(false); } }, [q, status]);
  useEffect(() => { load(1); }, [load]);
  const xem = async (id) => { try { const r = await getChiTietAdminLienHe(id); if (!r.success) throw new Error(r.message); setDetail(r.data); } catch (e) { await Swal.fire({ icon: "error", title: "Không thể tải chi tiết", text: e.response?.data?.message || e.message }); } };
  const doiTrangThai = async (item) => { const trangThaiMoi = item.trang_thai === "chua_xu_ly" ? "da_xu_ly" : "chua_xu_ly"; const ok = await Swal.fire({ icon: "warning", title: trangThaiMoi === "da_xu_ly" ? "Đánh dấu đã xử lý?" : "Chuyển về chưa xử lý?", showCancelButton: true, confirmButtonText: "Xác nhận", cancelButtonText: "Không" }); if (!ok.isConfirmed) return; try { const r = await putTrangThaiAdminLienHe(item.id, { trang_thai: trangThaiMoi }); if (!r.success) throw new Error(r.message); await Swal.fire({ icon: "success", title: r.message }); if (detail?.id === item.id) setDetail(r.data); load(meta?.current_page || 1); } catch (e) { await Swal.fire({ icon: "error", title: "Không thể cập nhật", text: e.response?.data?.message || e.message }); } };
  const badge = (item) => <span className={item.trang_thai === "da_xu_ly" ? "admin-room-status" : "admin-room-status admin-room-status-inactive"}>{item.trang_thai === "da_xu_ly" ? "Đã xử lý" : "Chưa xử lý"}</span>;
  return <AdminLayout title="Quản lý liên hệ" activeMenu="lien-he"><main className="admin-content"><div className="admin-intro admin-room-intro"><div><p className="section-kicker">HỘP THƯ LIÊN HỆ</p><h2>Quản lý liên hệ</h2><p>Theo dõi và đánh dấu các yêu cầu từ khách hàng.</p></div></div><div className="admin-booking-toolbar"><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Tên, email hoặc tiêu đề..." /><ReactSelect value={status} onChange={setStatus} isClearable placeholder="Tất cả trạng thái" options={[{ value: "chua_xu_ly", label: "Chưa xử lý" }, { value: "da_xu_ly", label: "Đã xử lý" }]} /><button type="button" onClick={() => load(1)}>Tìm kiếm</button></div>{loading ? <div className="admin-room-loading">Đang tải liên hệ...</div> : <><div className="admin-table-wrap"><table className="admin-room-table admin-booking-table"><thead><tr><th>Người gửi</th><th>Email</th><th>Tiêu đề</th><th>Ngày gửi</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{data.length === 0 ? <tr><td colSpan="6" className="admin-table-empty">Chưa có liên hệ phù hợp.</td></tr> : data.map((item) => <tr key={item.id}><td><strong>{item.ho_ten}</strong></td><td>{item.email}</td><td className="admin-description-cell">{item.tieu_de}</td><td>{formatDateTime(item.created_at)}</td><td>{badge(item)}</td><td><div className="admin-room-actions"><button className="admin-icon-button icon-navy" title="Xem chi tiết" onClick={() => xem(item.id)}><AdminIcon name="eye" /></button><button className={item.trang_thai === "da_xu_ly" ? "admin-icon-button icon-gold" : "admin-icon-button icon-green"} title="Đổi trạng thái" onClick={() => doiTrangThai(item)}><AdminIcon name={item.trang_thai === "da_xu_ly" ? "pause" : "check"} /></button></div></td></tr>)}</tbody></table></div><AdminPagination pagination={meta} onPageChange={load} /></>}</main>{detail && <div className="admin-modal-backdrop"><section className="admin-room-modal" role="dialog"><div className="admin-modal-head"><div><p className="section-kicker">CHI TIẾT LIÊN HỆ</p><h2>{detail.tieu_de}</h2></div><button type="button" onClick={() => setDetail(null)}>×</button></div><div className="admin-booking-detail"><section><h3>Người gửi</h3><p><b>{detail.ho_ten}</b><br />{detail.email}<br />{detail.so_dien_thoai || "Không có số điện thoại"}</p></section><section><h3>Trạng thái</h3><p>{badge(detail)}<br />{formatDateTime(detail.created_at)}</p></section><section className="admin-detail-full"><h3>Nội dung</h3><p className="admin-contact-message">{detail.noi_dung}</p></section></div></section></div>}</AdminLayout>;
}
